enchant @a[hasitem={location=slot.weapon.mainhand,item=spimton:bronze_boots}] protection 1
enchant @a[hasitem={location=slot.weapon.mainhand,item=spimton:bronze_helmet}] protection 1
enchant @a[hasitem={location=slot.weapon.mainhand,item=spimton:bronze_chestplate}]  protection 1
enchant @a[hasitem={location=slot.weapon.mainhand,item=spimton:bronze_leggings}] protection 1
enchant @a[hasitem={location=slot.weapon.mainhand,item=spimton:bronze_sword}] sharpness 1
enchant @a[hasitem={location=slot.weapon.mainhand,item=spimton:bronze_pickaxe}] efficiency 1
enchant @a[hasitem={location=slot.weapon.mainhand,item=spimton:bronze_axe}] efficiency 1
enchant @a[hasitem={location=slot.weapon.mainhand,item=spimton:bronze_shovel}] efficiency 1
enchant @a[hasitem={location=slot.weapon.mainhand,item=spimton:bronze_hoe}] efficiency 1
enchant @a[hasitem={location=slot.weapon.mainhand,item=spimton:bronze_spear}] sharpness 1