enchant @a[hasitem={location=slot.weapon.mainhand,item=spimton:steel_boots}] unbreaking 2
enchant @a[hasitem={location=slot.weapon.mainhand,item=spimton:steel_leggings}] unbreaking 2
enchant @a[hasitem={location=slot.weapon.mainhand,item=spimton:steel_chestplate}] unbreaking 2
enchant @a[hasitem={location=slot.weapon.mainhand,item=spimton:steel_helmet}] unbreaking 2
enchant @a[hasitem={location=slot.weapon.mainhand,item=spimton:steel_axe}] unbreaking 2
enchant @a[hasitem={location=slot.weapon.mainhand,item=spimton:steel_sword}] unbreaking 2
enchant @a[hasitem={location=slot.weapon.mainhand,item=spimton:steel_pickaxe}] unbreaking 2
enchant @a[hasitem={location=slot.weapon.mainhand,item=spimton:steel_shovel}] unbreaking 2
enchant @a[hasitem={location=slot.weapon.mainhand,item=spimton:steel_hoe}] unbreaking 2
enchant @a[hasitem={location=slot.weapon.mainhand,item=spimton:steel_spear}] unbreaking 2